# Generated by Django 5.0.6 on 2024-10-26 14:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inser_time', models.DateField(default=datetime.date.today)),
                ('update_time', models.DateField(default=datetime.date.today)),
                ('user_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('short_intorduction', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('established_date', models.DateField()),
                ('type_of_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szarvaskerteszet.businesstypes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szarvaskerteszet.ownerdetails')),
            ],
        ),
    ]
