# Generated by Django 5.0.6 on 2024-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szarvaskerteszet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='contact_email',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
